# Generated by Django 4.2.4 on 2023-08-31 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal', models.TextField()),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mealplanner_app.day')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mealplanner_app.week')),
            ],
            options={
                'verbose_name_plural': 'meals',
            },
        ),
        migrations.AddField(
            model_name='day',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mealplanner_app.week'),
        ),
    ]
